### ISSUE TITLE
Broken desktop file

### ISSUE THREAD

**Issue by probonopd** [cyfrost/todoist-linux#2]
```
/tmp/.mount_appimaRHCN4k/todoist.desktop: error: value "Internet;Office;Utility;Productivity;" for key "Categories" in group "Desktop Entry" contains an unregistered value "Internet"; values extending the format should start with "X-"
/tmp/.mount_appimaRHCN4k/todoist.desktop: hint: value "Internet;Office;Utility;Productivity;" for key "Categories" in group "Desktop Entry" contains more than one main category; application might appear more than once in the application menu
/tmp/.mount_appimaRHCN4k/todoist.desktop: error: value "Internet;Office;Utility;Productivity;" for key "Categories" in group "Desktop Entry" contains an unregistered value "Productivity"; values extending the format should start with "X-"
```

Please run the desktop file through desktop-file-validate and make sure it passes the [menu spec](https://standards.freedesktop.org/menu-spec/latest/apa.html).

Reference:
https://github.com/AppImage/appimage.github.io/pull/754

**Comment by cyfrost** [comment]
Fixed, Thanks!

https://github.com/cyfrost/todoist-linux/commit/20dd0cebaea57e38ff3870aa67c4b4de46c55fec#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

**Comment by probonopd** [comment]
Thank you very much. If you could ping me once a release containing this fix is available, then I can re-test and add the application to the AppImageHub central directory of available AppImages.

**Comment by cyfrost** [comment]
Release available:

(Direct download --x64 AppImage)
https://github.com/cyfrost/todoist-linux/releases/download/v1.0/Todoist-1.0.1-x86_64.AppImage

**Comment by probonopd** [comment]
Thank you very much.
