### ISSUE TITLE
Suggestion: Ask Doist to put your app on their download page

### ISSUE THREAD

**Issue by ruedigerkupper** [cyfrost/todoist-linux#7]
Hi! Your application is a real good drop-in for a "real" desktop application. Looking ad Doist's downoad page, you see that they do not yet offer a Todoist desktop application for download: https://todoist.com/downloads
They might want to link to your project or offer download of the install packages from that page?

**Comment by cyfrost** [comment]
Heh thanks! I'm not even sure, entire credits go to [@KryDos ](https://github.com/KryDos/todoist-linux) for taking the first knife at this project. Although I'd consider dropping them an email I'm not sure if it'll ever go through.
