### ISSUE TITLE
Add zoom in/ zoom out option

### ISSUE THREAD

**Issue by vv12131415** [cyfrost/todoist-linux#9]
I've noticed that I can't zoom in. That is a problem since I use 4k monitor and everything becomes tiny.

**Comment by void-m4110c** [comment]
Same here. Any progress on this would be really great!

**Comment by cyfrost** [comment]
Hey, Hi.

I'm working on it. It should be fairly trivial, let me see if it works once I'm done with refactoring the codebase.

**Comment by void-m4110c** [comment]
Nice! Once, done, I'll be glad to test :-)
